Update on_pull_request.yml

diff --git a/.github/workflows/on_pull_request.yml b/.github/workflows/on_pull_request.yml
--- a/.github/workflows/on_pull_request.yml
+++ b/.github/workflows/on_pull_request.yml
@@ -19,7 +19,8 @@ jobs:
                 then echo "Missing secret: $v" missing=1 
                 fi done 
                 if [ $missing -eq 1 ]; 
-                then echo "Required secrets are not set. Exiting." exit 1 fi
+                then echo "Required secrets are not set. Exiting." exit 1 
+                fi
             
             - name: Configure AWS credentials
               uses: aws-actions/configure-aws-credentials@v2 
