Clean

diff --git a/.github/workflows/on_pull_request.yml b/.github/workflows/on_pull_request.yml
--- a/.github/workflows/on_pull_request.yml
+++ b/.github/workflows/on_pull_request.yml
@@ -12,33 +12,26 @@ jobs:
             - name: Checkout
               uses: actions/checkout@v2
 
-            - name: Check required secrets
-              shell: bash
-              env:
-                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-                AWS_REGION: ${{ secrets.AWS_REGION }}
-                S3_ANALYZE_BUCKET: ${{ secrets.S3_ANALYZE_BUCKET }}
-              run: |
-                missing=0
-                for v in AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_REGION S3_ANALYZE_BUCKET; do
-                  if [ -z "${!v}" ]; then
-                    echo "Missing secret: $v"
-                    missing=1
-                  fi
-                done
-            
-                if [ "$missing" -eq 1 ]; then
-                  echo "Required secrets are not set. Exiting."
-                  exit 1
-                fi
+            - name: Check required secrets 
+              shell: 
+                bash 
+              env: 
+                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
+                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
+                AWS_REGION: ${{ secrets.AWS_REGION }} 
+                S3_ANALYZE_BUCKET: ${{ secrets.S3_ANALYZE_BUCKET }} 
+              run: | 
+                    set -x missing=0; 
+                    for v in AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_REGION S3_ANALYZE_BUCKET; 
+                    do if [ -z "${!v}" ]; then echo "Missing secret: $v" missing=1 fi done
+                    if [ "$missing" -eq 1 ]; then echo "Required secrets are not set. Exiting." exit 1 fi
             
             - name: Configure AWS credentials
               uses: aws-actions/configure-aws-credentials@v2 
               with: 
-                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
-                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
-                aws-region: ${{ secrets.AWS_REGION }}
+                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
+                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
+                  aws-region: ${{ secrets.AWS_REGION }}
 
             - name: Upload Images to S3
               run: |
